FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src/ src/
COPY infrastructure/ infrastructure/
COPY domain/ domain/
CMD ["python", "-m", "src.scraper.scraper", "--kind", "trip", "--dir", "./scraper_data/trip_data"]

