
services:
  db:
    image: postgis/postgis:15-3.3        # PostGIS-Image basierend auf PostgreSQL 15, PostGIS 3.3
    container_name: pg_postgis
    restart: unless-stopped
    environment:
      POSTGRES_USER: radverkehr           # DB-User
      POSTGRES_PASSWORD: passwort123  
      POSTGRES_DB: radstationen           # Datenbankname
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d   # <- hier werden alle *.sql beim Erst-Run ausgeführt
      - ./data:/data
    ports:
      - "5432:5432"                       # Exponiere Port 5432 beim Host

  #  pgAdmin zum Verwalten via Web-GUI (http://localhost:8080)
  pgadmin:
    image: dpage/pgadmin4:7.5
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: grafcem98@gmail.com
      PGADMIN_DEFAULT_PASSWORD: passwort123
    ports:
      - "8080:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin

  scraper:
    build: .
    container_name: scraper
    command: >
      python -m src.scraper.scraper --kind geojson --dir ./scraper_data/live --interval 60
    volumes:
      - ./scraper_data:/app/scraper_data
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: radverkehr
      PGPASSWORD: passwort123
      PGDATABASE: radstationen
    depends_on:
      - db

  trip_scraper:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    container_name: trip_scraper
    command: >
      python -m src.scraper.scraper --kind trip --dir ./scraper_data/trip_data
    volumes:
      - ./scraper_data:/app/scraper_data
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: radverkehr
      PGPASSWORD: passwort123
      PGDATABASE: radstationen
    depends_on:
      - db

volumes:
  pgdata:
  pgadmindata:
